[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/klipper_user/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    192.168.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FC00::/7
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager fluidd]
path: /home/klipper_user/fluidd
repo: fluidd-core/fluidd
channel: stable
type: web
persistent_files:
    config.json

[update_manager fluidd-config]
managed_services: klipper
origin: https://github.com/fluidd-core/fluidd-config.git
path: /home/klipper_user/fluidd-config
primary_branch: master
type: git_repo

[update_manager mainsail]
path: /home/klipper_user/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[include octoeverywhere-system.cfg]

[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main

[update_manager klipper]
type: git_repo
path: ~/klipper
origin: https://github.com/KalicoCrew/kalico.git
env: ~/klippy-env/bin/python
requirements: scripts/klippy-requirements.txt
install_script: scripts/install-os-packages.sh
is_system_service: False